# Generated by Django 4.0.4 on 2022-05-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='u_address',
            field=models.CharField(max_length=200, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phonenum',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='전화번호'),
        ),
    ]
