# Generated by Django 4.0.4 on 2022-05-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_u_id_alter_user_u_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_phonenum',
            field=models.CharField(max_length=200, null=True, verbose_name='전화번호'),
        ),
    ]
