# Generated by Django 4.0.1 on 2022-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
