# Generated by Django 4.0.4 on 2022-05-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='u_nickname',
        ),
    ]
